# Generated by Django 5.1.1 on 2024-09-16 23:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_alter_avatar_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avatar',
            name='imagen',
            field=models.ImageField(blank=True, default='avatars/default-avatar.png', null=True, upload_to='avatars'),
        ),
    ]
