# Generated by Django 5.1.1 on 2024-09-16 00:24

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miaplicacion', '0004_alter_blog_imagen_alter_blog_titulo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='fecha_publicacion',
        ),
        migrations.AddField(
            model_name='blog',
            name='fecha',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
