# Generated by Django 5.1.1 on 2024-09-16 02:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Miaplicacion', '0005_remove_blog_fecha_publicacion_blog_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='titulo',
            field=models.CharField(max_length=50),
        ),
    ]
